USE [master]
GO
/****** Object:  Database [MordidaDivina]    Script Date: 04/03/2024 08:59:41 p. m. ******/
CREATE DATABASE [MordidaDivina]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MordidaDivina', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MordidaDivina.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MordidaDivina_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\MordidaDivina_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [MordidaDivina] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MordidaDivina].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MordidaDivina] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MordidaDivina] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MordidaDivina] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MordidaDivina] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MordidaDivina] SET ARITHABORT OFF 
GO
ALTER DATABASE [MordidaDivina] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MordidaDivina] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MordidaDivina] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MordidaDivina] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MordidaDivina] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MordidaDivina] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MordidaDivina] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MordidaDivina] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MordidaDivina] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MordidaDivina] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MordidaDivina] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MordidaDivina] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MordidaDivina] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MordidaDivina] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MordidaDivina] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MordidaDivina] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MordidaDivina] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MordidaDivina] SET RECOVERY FULL 
GO
ALTER DATABASE [MordidaDivina] SET  MULTI_USER 
GO
ALTER DATABASE [MordidaDivina] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MordidaDivina] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MordidaDivina] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MordidaDivina] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MordidaDivina] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MordidaDivina] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MordidaDivina', N'ON'
GO
ALTER DATABASE [MordidaDivina] SET QUERY_STORE = ON
GO
ALTER DATABASE [MordidaDivina] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [MordidaDivina]
GO
/****** Object:  Table [dbo].[carrito]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[carrito](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[usuarioID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[categorias]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[categorias](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[detalleCarrito]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[detalleCarrito](
	[carritoId] [bigint] NOT NULL,
	[productoId] [bigint] NOT NULL,
	[cantidad] [int] NOT NULL,
	[total] [decimal](10, 2) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[detallePedido]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[detallePedido](
	[pedidoId] [bigint] NOT NULL,
	[productoId] [bigint] NOT NULL,
	[cantidad] [int] NOT NULL,
	[total] [decimal](10, 2) NOT NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[direcciones]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[direcciones](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[provincia] [varchar](255) NOT NULL,
	[canton] [varchar](255) NOT NULL,
	[distrito] [varchar](255) NOT NULL,
	[direccionExacta] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[errores]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[errores](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[codigo] [varchar](255) NOT NULL,
	[descripcion] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[pedido]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[pedido](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[usuarioID] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[productos]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[productos](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[categoriaId] [bigint] NOT NULL,
	[nombre] [varchar](255) NULL,
	[descripcion] [varchar](255) NOT NULL,
	[precio] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[roles]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[roles](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 04/03/2024 08:59:41 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[rolId] [bigint] NOT NULL,
	[direccionID] [bigint] NOT NULL,
	[nombre] [varchar](255) NOT NULL,
	[apellidos] [varchar](255) NOT NULL,
	[email] [varchar](255) NOT NULL,
	[contrasenna] [varchar](255) NOT NULL,
	[activo] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[carrito]  WITH CHECK ADD  CONSTRAINT [FK_CarritoUsuario] FOREIGN KEY([usuarioID])
REFERENCES [dbo].[usuarios] ([id])
GO
ALTER TABLE [dbo].[carrito] CHECK CONSTRAINT [FK_CarritoUsuario]
GO
ALTER TABLE [dbo].[detalleCarrito]  WITH CHECK ADD  CONSTRAINT [FK_CarritoId] FOREIGN KEY([carritoId])
REFERENCES [dbo].[carrito] ([id])
GO
ALTER TABLE [dbo].[detalleCarrito] CHECK CONSTRAINT [FK_CarritoId]
GO
ALTER TABLE [dbo].[detalleCarrito]  WITH CHECK ADD  CONSTRAINT [FK_ProductoId] FOREIGN KEY([productoId])
REFERENCES [dbo].[productos] ([id])
GO
ALTER TABLE [dbo].[detalleCarrito] CHECK CONSTRAINT [FK_ProductoId]
GO
ALTER TABLE [dbo].[detallePedido]  WITH CHECK ADD  CONSTRAINT [FK_PedidoId] FOREIGN KEY([pedidoId])
REFERENCES [dbo].[pedido] ([id])
GO
ALTER TABLE [dbo].[detallePedido] CHECK CONSTRAINT [FK_PedidoId]
GO
ALTER TABLE [dbo].[detallePedido]  WITH CHECK ADD  CONSTRAINT [FK_ProductoIdPedido] FOREIGN KEY([productoId])
REFERENCES [dbo].[productos] ([id])
GO
ALTER TABLE [dbo].[detallePedido] CHECK CONSTRAINT [FK_ProductoIdPedido]
GO
ALTER TABLE [dbo].[pedido]  WITH CHECK ADD  CONSTRAINT [FK_PedidoUsuario] FOREIGN KEY([usuarioID])
REFERENCES [dbo].[usuarios] ([id])
GO
ALTER TABLE [dbo].[pedido] CHECK CONSTRAINT [FK_PedidoUsuario]
GO
ALTER TABLE [dbo].[productos]  WITH CHECK ADD  CONSTRAINT [FK_CategoriaProducto] FOREIGN KEY([categoriaId])
REFERENCES [dbo].[categorias] ([id])
GO
ALTER TABLE [dbo].[productos] CHECK CONSTRAINT [FK_CategoriaProducto]
GO
ALTER TABLE [dbo].[usuarios]  WITH CHECK ADD  CONSTRAINT [FK_DireccionUsuario] FOREIGN KEY([direccionID])
REFERENCES [dbo].[direcciones] ([id])
GO
ALTER TABLE [dbo].[usuarios] CHECK CONSTRAINT [FK_DireccionUsuario]
GO
ALTER TABLE [dbo].[usuarios]  WITH CHECK ADD  CONSTRAINT [FK_RolUsuario] FOREIGN KEY([rolId])
REFERENCES [dbo].[roles] ([id])
GO
ALTER TABLE [dbo].[usuarios] CHECK CONSTRAINT [FK_RolUsuario]
GO
USE [master]
GO
ALTER DATABASE [MordidaDivina] SET  READ_WRITE 
GO
